FORMAT: 1A
HOST: https://api.healthdata.be

# HealthData API
Collection of all the different APIs provided by HealthData.

##Allowed HTTPs requests:

- `POST` - To create resource
- `PUT` - To update resource
- `GET` - Get a resource or list of resources
- `DELETE` - To delete resource

##Description Of Usual Server Responses

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 302 `Redirected` - the request is redirected to the URL in the Location header.
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.
- 429 `Too Many Requests` - exceeded GoodData API limits. Pause requests, wait up to one minute, and try again. 
- 503 `Service Unavailable` - service is temporary unavailable (e.g. scheduled Platform Maintenance). Try again later.

# Group Annotations API

# Group Bulk API
Bulk-related resources of the **HealthData API**

## Bulks [/bulks]

### Submit a list of Datacollection instances [POST]
Store a list of Datacollection instances.
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {   
                "datacollection instances": [
                    {"JSON content datacollection instance 1"},
                    {"JSON content datacollection instance 2"},
                    {"JSON content datacollection instance 3"}
                ]
            }
+ Response 200

# Group Data Reference API
DataReference-related resources of the **HealthData API**

The Codelist resource has the following attributes:

- id
- code
- created_at
- description_nl-BE
- description_fr-BE
- description_en-US

The states *id* and *created_at* are assigned by the Collections API at the moment of creation.

## Data Reference [/datareferences/{name}/{version}]

### GET
This API call will redirect you the Data Reference with the id that matches the provided name and version.
+ Parameters
    + name (required, string, `"postal_codes"`) ... `name` of the Data Reference.
    + version (required, string, `"v2"`) ... `version` of the Data Reference.

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
    
            {
            }

+ Response 302

    + Headers
    
            Location: "http://healthdata.apiary-mock.com/datareferences/2"



## Data References - Code & Language [/datareferences/id/{code}/{language}]

+ Parameters
    + id (required, string, `"1"` ) ... `id` of the Data Reference entry.
    + code (required, string, `"code"`) ... `code` of the Data Reference entry.
    + language = `en-US`(optional, string, `en-US`)

        'language' of the Data Reference entry.

        + Values
            + `nl-BE`
            + `fr-BE`
            + `en-US`

+ Model (application/hal+json)

    JSON representation of a Data Reference resource. 

   + Body

            {
                "_links": {
                    "self": { "href": "http://healthdata.apiary-mock.com/datareferences/1" }
                },
                "id": "1",
                "code": "code",
                "created_at": "2014-06-10T02:15:15Z",
                "description_nl-BE": "Nederlandstalige beschrijving" 
            }

### GET
This API call will GET you the Data Reference with the provided code and language.
            
+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
    + Body
    
            {
            }

+ Response 200 (application/hal+json)

    [Data References - Code & Language][]

## Data Reference - QueryString parameters [/datareferences/id{?created_at,description_nl_BE,description_fr_BE,description_en_US}]

List all existing Datacollections that match the given QueryString parameters.

Possible QueryString parameters:

- created_at
- description_nl_BE
- description_fr_BE
- description_en_US

+ Parameters
    + id (required, string, `"1"` ) ... `id` of the Data Reference entry.

 
### GET

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {
            }

+ Response 200 (application/hal+json)

    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datareferences"
                    }
                },
                "_embedded": {
                    "datareferences": [
                        {
                            "_links": {
                                "self": { "href": "http://healthdata.apiary-mock.com/datareferences/1" }
                            },
                            "id": "1",
                            "code": "code",
                            "created_at": "2014-06-10T02:15:15Z",
                            "description_nl-BE": "Nederlandstalige beschrijving" 
                        },
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datareferences/2"
                                }
                            },
                            "id": "2", 
                            "code": "code",
                            "created_at": "2014-06-10T02:15:15Z",
                            "description_nl-BE": "Nederlandstalige beschrijving" 
                        }
                    ]
                }
            }
            
# Group Datacollection Definition API
DataCollectionDefinitions-related resources of the **HealthData API**

A single DataCollectionDefinition object with all its details

The DataCollectionDefinition resource has the following attributes:

- id
- name
- language
- created_at
- published
- valid_from
- valid_till
- description
- content

The states *id* and *created_at* are assigned by the Collections API at the moment of creation.

## Datacollection Definition - ID [/datacollectiondefinitions/{id}]

+ Parameters
    + id (required, string, `"1"`) ... `ID` of the DataCollectionDefinition. Has example value.

+ Model (application/hal+json)

    JSON representation of a DataCollectionDefinition resource. 

    + Body

            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"
                    }
                },
                "id": "1",
                "name": "Datacollection definition 1",
                "created_at": "2014-06-10T02:15:15Z",
                "valid_from": "2014-06-10T00:00:00Z",
                "valid_till": "2024-06-10T00:00:00Z",
                "description": "Datacollection definition 1 description",
                "content": "JSON content"
            }

### GET
This API call will GET you the Datacollection definition with the provided ID.

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
    
            {
            }
+ Response 200
    [Datacollection Definition - ID][]

### DELETE
This API call will DELETE your defined Datacollection definition. 
Only Project ADMIN can do this action and only data collection definitions with the published property set to false can be deleted.

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
+ Response 204

+ Response 403

        You are not allowed to delete a data collection definition that is already published.

+ Response 404

        The data collection definition you want to delete does not exist anymore.

### PUT
This API call will UPDATE your defined Datacollection definition. It is important to state that only the description, published and validTill properties can be updated.
The other fields are immutable. 

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version

    + Body
    
            Published: true
            "valid_till": "2025-06-10T00:00:00Z",
            "description": "updated description"
            
+ Response 204

## Datacollection Definition - Name & Version [/datacollectiondefinitions/{name}/{version}]

### GET
This API call will GET you the Datacollection definition with the provided name and version.
+ Parameters
    + name (required, string, `"register 1"`) ... `name` of the DataCollectionDefinition. Has example value.
    + version (required, string, `"v2"`) ... `version` of the DataCollectionDefinition. Has example value.

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
    
            {
            }

+ Response 302

    + Headers
    
            Location: "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"

## Datacollection Definitions [/datacollectiondefinitions/]

### GET

List all existing Datacollection definitions that the user is authorized to see. 

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {
            }

+ Response 200 (application/hal+json)

    + Headers
    
            Accept-Ranges: "datacollectiondefinitions"
            Content-Range: "datacollectiondefinitions 0-1/10

    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions"
                    }
                },
                "_embedded": {
                    "datacollectiondefinitions": [
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"
                                }
                            },
                            "id": "1", 
                            "name": "Datacollection definition 1",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "valid_from": "2014-06-10T00:00:00Z",
                            "valid_till": "2024-06-10T00:00:00Z",
                            "published": false
                            "description": "Description of DataCollection definition 1.",
                            "content": "JSON content"
                        },
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/2"
                                }
                            },
                            "id": "2", 
                            "name": "Datacollection definition 2",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "valid_from": "2014-06-10T00:00:00Z",
                            "valid_till": "2024-06-10T00:00:00Z",
                            "published": false
                            "description": "Description of DataCollection definition 2.",
                            "content": "JSON content"
                        }
                    ]
                }
            }

+ Response 206 (application/hal+json)
    + Headers
    
            Accept-Ranges: "datacollectiondefinitions"
            Content-Range: "datacollectiondefinitions 0-1/10

    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions"
                    }
                },
                "_embedded": {
                    "datacollectiondefinitions": [
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"
                                }
                            },
                            "id": "1", 
                            "name": "Datacollection definition 1",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "valid_from": "2014-06-10T00:00:00Z",
                            "valid_till": "2024-06-10T00:00:00Z",
                            "published": false
                            "description": "Description of DataCollection definition 1.",
                            "content": "JSON content"
                        },
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/2"
                                }
                            },
                            "id": "2", 
                            "name": "Datacollection definition 2",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "valid_from": "2014-06-10T00:00:00Z",
                            "valid_till": "2024-06-10T00:00:00Z",
                            "published": false
                            "description": "Description of DataCollection definition 2.",
                            "content": "JSON content"
                        }
                    ]
                }
            }

### POST
Create a new Datacollection definition.
+ Request (application/json)
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    
    + Body
            
            {   
                "name": "Datacollection definition 1",
                "language": "nl",
                "description": "Datacollection definition 1 description.",
                "content": "JSON content" 
            }

+ Response 201 (application/hal+json)

    + Body
            
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"
                    }
                },
                "id": "1",
                "name": "Datacollection definition 1",
                "created_at": "2014-06-10T02:15:15Z",
                "valid_from": "2014-06-10T00:00:00Z",
                "valid_till": "2024-06-10T00:00:00Z",
                "published": false
                "description": "Datacollection definition 1 description",
                "content": "JSON content"
            }

## Datacollection Definition - QueryString parameters [/datacollectiondefinitions{?name,valid_from,valid_till,description}]

List all existing Datacollections that match the given QueryString parameters.
 
### GET

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {
            }

+ Response 200 (application/hal+json)

    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions"
                    }
                },
                "_embedded": {
                    "datacollectiondefinitions": [
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/1"
                                }
                            },
                            "id": "1", 
                            "name": "Datacollection definition 1",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "description": "Description of DataCollection definition 1.",
                            "content": "JSON content"
                        },
                        {
                            "_links": {
                                "self": {
                                    "href": "http://healthdata.apiary-mock.com/datacollectiondefinitions/2"
                                }
                            },
                            "id": "2", 
                            "name": "Datacollection definition 2",
                            "language": "nl",
                            "created_at": "2014-06-10T02:15:15Z",
                            "description": "Description of DataCollection definition 2.",
                            "content": "JSON content"
                        }
                    ]
                }
            }

# Group Data Provisioning API
Interface exposed to external parties that want to upload prefilling data.

## Data Provisioning [/dataprovisioning]

### POST

+ Request (application/json)
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
            Data type: "csv"
    
    + Body
            
            {   
                "content": "data file"
            }

+ Response 201

# Group Documents API
Document-related resources  of the **HealthData API**

The Document resource has the following attributes:

- id
- name
- description
- created_at
- content

The states *id* and *created_at* are assigned by the Documents API at the moment of creation.

## Document [/documents]

### Create a document item [POST]
Store a new document item
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {   
                "name"          : "name"
                "description"   : "description"
                "content"       : "JSON content" 
            }
+ Response 200 (application/json)
    
    + Body
            
            {   
                "ID"    : "ID of the created document item" 
            }

## Document - ID [/documents/{id}]

+ Parameters
    + id (required, string, `"1"`) ... `ID` of the Document. Has example value.

+ Model (application/hal+json)

    JSON representation of a Documents resource. 

    + Body

            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/documents/1"
                    }
                },
                "id": "1",
                "name": "Document 1",
                "description": "Document 1 description",
                "created_at": "2014-06-10T02:15:15Z",
                "content": "JSON content"
            }

### Get a document item [GET]
This API call will GET you the Document with the provided ID.

+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {
            }
+ Response 200
    [Document - ID][]

### Delete a document item [DELETE]
This API call will DELETE the defined Document.

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
+ Response 204

# Group Transaction API
Transaction-related resources of the **HealthData API**

The transactional API will offer a programmatic alternative to the forms (the human interface). 
This API will be accessible by calling applications wanting to submit structured data to HD4DP software.

## Transaction [/transactions]

### Submit a Datacollection instance [POST]
Store a new Datacollection instance.
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {   
                "content": "JSON content" 
            }
+ Response 200

# Group Validation API
API used for the validation of data collection instances.

## Validation [/validations]

### POST
Perform a validation of a data collection instance.
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
        
            {   
                "content"   : "JSON content"
            }
+ Response 200 (application/json)
    
    + Body
        
            {   
                "status"    : "OK"
                "content"   : "JSON content"
            }

# Group Workflow API
Workflow-related resources of the **HealthData API**

## Workflow [/workflows]

+ Model (application/hal+json)

    JSON representation of a DataCollectionDefinition resource. 

    + Body

            {
                "_links": {
                    "self": { "href": "http://healthdata.apiary-mock.com/workflows/1" },
                    "content": { "href": "http://healthdata.apiary-mock.com/documents/1" }
                },
                "id": "1",
                "status": "New"
            }

### Create a workflow item [POST]
Store a new workflow item
+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
        
            {   
                "status"    : "workflow status" 
                "content"   : "JSON content"
            }
+ Response 200 (application/json)
    
    [Workflow][]

## Workflow - ID [/workflows/{id}]

+ Parameters
    + id (required, string, `"1"`) ... `ID` of the Workflow item. Has example value.

+ Model (application/hal+json)

    JSON representation of a DataCollectionDefinition resource. 

    + Body

            {
                "_links": {
                    "self": { "href": "http://healthdata.apiary-mock.com/workflows/1" },
                    "content": { "href": "http://healthdata.apiary-mock.com/documents/1" }
                },
                "id": "1",
                "status": "New"
            }

### Retrieve a workflow item [GET]
Get a workflow item with the provided ID

+ Request
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version

+ Response 200 (application/hal+json)

    [Workflow - ID][]

### Update a workflow item [PUT]
Update an existing workflow item

+ Request (application/json)
    
    + Headers
    
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {   
                "status"    : "workflow status" 
            }
+ Response 200

    [Workflow - ID][]
    
### Delete a workflow item [DELETE]
Delete an existing workflow item

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
+ Response 204

## Workflow - QueryString parameters [/workflows{?status}]

List all existing Datacollections that match the given QueryString parameters.
 
Possible QueryString parameters:

- status
 
### GET

+ Request
    
    + Headers
        
            Authorization: "Bearer <<token>>"
            API version : version
    + Body
            
            {
            }

+ Response 200 (application/hal+json)

    + Body
    
            {
                "_links": {
                    "self": {
                        "href": "http://healthdata.apiary-mock.com/workflows"
                    }
                },
                "_embedded": {
                    "workflows": [
                        {
                           "_links": {
                                "self": { "href": "http://healthdata.apiary-mock.com/workflows/1" },
                                "content": { "href": "http://healthdata.apiary-mock.com/documents/1" }
                            },
                            "id": "1",
                            "status": "NEW"
                        },
                        {
                            "_links": {
                                "self": { "href": "http://healthdata.apiary-mock.com/workflows/2" },
                                "content": { "href": "http://healthdata.apiary-mock.com/documents/2" }
                            },
                            "id": "2",
                            "status": "NEW"
                        }
                    ]
                }
            }